language: python
sudo: required
dist: xenial
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.7-dev"

before_install:
  - pip install codecov
  - pip install pytest-cov

install:
  - pip install -e .

script:
  - pytest --cov-report=xml --cov=videotoframes tests/

after_success:
  - codecov